name: Second Workflow

on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed

jobs:
  second-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print from Second Job
        run: echo "This is the second job."
