name: First Job

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print HI
        run: echo HI

      - name: Wait for 1 minute
        run: sleep 60


