name: First Job

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print HI
        run: echo HI

      - name: Wait for 1 minute
        run: sleep 60

      - name: Trigger Second Job
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/<username>/<repository>/actions/workflows/2.yml/dispatches \
          -d '{"ref":"main"}'

