name: Run Python Script

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with the version of Python you need

    - name: Run Python script
      run: |
        pip install psutil

        python main.py
        # Replace with the path to your Python script

