name: Workflow 1

on:
  push:
    branches:
      - Master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add your build steps here
      - name: Run build
        run: echo "Running build for Workflow 1"

      # Add a 60-second wait time
      - name: Wait for 60 seconds
        uses: actions/github-script@v6
        with:
          script: |
            const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
            await delay(60000);

      # Trigger Workflow 2
      - name: Trigger Workflow 2
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-workflow-2
